version: '3.4'

services:
    eliboo.api:
        image: ${DOCKER_REGISTRY-}elibooapi
        build:
            context: .
            dockerfile: Eliboo.Api/Dockerfile
        depends_on:
            - postgres
        networks:
            - eliboo-app

    postgres:
        image: postgres:13.1
        restart: always
        ports:
            - 5432:5432
        networks:
            - eliboo-app

networks:
    eliboo-app:
        driver: bridge